### ISSUE TITLE
Error in workflow 'com.razor.rates'

### ISSUE THREAD

**Issue by igorshubovych** [kennedyoliveira/alfred-rates#16]
This one works "rate 100 uah usd"
This one does not work "rate 100 usd uah".

UAH (uah) - the code for Ukrainian Hryvnya.

![Screenshot](https://api.monosnap.com/rpc/file/download?id=oxaJaSoGfKERPTclhk63DhbAtbXLf8)

**Comment by kennedyoliveira** [comment]
Hello @igorshubovych, there is another issue about this problem here and i really don't know what's going on because on my machine it just works fine, can you pass some more information about your system to help me find out?

What OS X version are you using?
What python version?
What your mac os x language?
What alfred version are you using?
What is the current divisor set in your Rates settings?

I guess with this info maybe i can find out something.

Thank you!

![fullscreen_4_6_16__11_08_am](https://cloud.githubusercontent.com/assets/7723330/14319516/e1fa301e-fbe7-11e5-88db-75e8457f37ab.png)

**Comment by igorshubovych** [comment]
> What OS X version are you using?

OSX: 10.11.4 (15E65)

> What python version?

Python 2.7.11

> What your mac os x language?

English

> What alfred version are you using?

2.8.3
10th Mar 2016

> What is the current divisor set in your Rates settings?

Not sure what you mean.

**Comment by kennedyoliveira** [comment]
Thank you for the info man, the divisor settings is a configuration in rates for divisor ',' or '.' and the decimal places, you can set a new with `ratesetdivisor` and get it with `rategetdivisor`

**Comment by igorshubovych** [comment]
`ratesetdivisor  .`
This one fixed everything. I have English system language, but Ukrainian locale. Probably it is better to mention this recipe in README.md FAQ section or so.

**Comment by kennedyoliveira** [comment]
Humm i need to check exactly why this problem, because it should work even if you not set the divisor, because i get one based on you currently localte, anyway, for the moment i'll update the readme telling it until i found out whats causing this problem.

**Comment by hootlex** [comment]
@kennedyoliveira I am still getting this error on v2.4.3 after running `ratesetdivisor .`

**Comment by emilerl** [comment]
Using `ratesetdivisor .` followed by `rateclear` and `ratesetdivisor ,` solved the problem for me.
