### ISSUE TITLE
List Rates

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#7]
Hello,

More a feature request than an issue:

Would it be possible to show a list of currency translations in one shot. For e.g.

1 EUR INR
1 INR USD
1 EUR USD

All, with one command.. 

BTW: Currently I have three separate shortcuts configured to show all these separately.

**Comment by kennedyoliveira** [comment]
@jothirams, i guess it's possible, but what command would be easy? something like a "," to separe the list our ";" ?

Something like:

```
1 EUR INR, 1 INR USD, 1 EUR USD?
```

Would it help? You have any suggestion about the command?

**Comment by jothirams** [comment]
Hi Kennedy,

Yes the comma is a good idea.

**Comment by kennedyoliveira** [comment]
@jothirams Hello!

i'm working on that issue and implemented two things.

Various command using a ';', because the ',' ca be used for division.
New way to show a conversion in various currencnies.

`1000 GBP USD CAD EUR`

the result will be 1000 GBP in USD, 1000 GBP in CAD and 1000 GBP in EUR.

Now your problem can be solved like that: 

```
1 EUR INR; 1 INR USD
```

Check below:

![fullscreen_7_25_15__16_20](https://cloud.githubusercontent.com/assets/7723330/8890928/5132a6a0-32e9-11e5-8b0d-e6cc097839a4.png)

I'm doing some tests and 'll release it soon

**Comment by kennedyoliveira** [comment]
@jothirams, checkout the new version!

**Comment by sundarv85** [comment]
@kennedyoliveira Awesome!!! It works gracefully.. Thanks a lot for such a quick addition of this feature..

**Comment by jothirams** [comment]
@kennedyoliveira Awesome.. It just works superbly.. Thanks a lot for the quick support.
