### ISSUE TITLE
Automatic Upgrade

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#8]
Hello,

When there is a new update, and when I try "1 EUR INR" - it says, there is a new update, please use rate update to update it.

Is it possible to show that in the second line, so that the users can control when to update. Now I’m forced to update it.

Also, the configured shortcuts are lost when the update happens - as it is installed as a new workflow. Is there a way to handle this in Alfred2 itself or is that the known behaviour.

**Comment by kennedyoliveira** [comment]
Hello @jothirams!

About the update, yeah its a good ideia, i'll work on that.

About you configured shortcuts, i guess it's impossible to keep them, because the update replaces the workflow, so the shortcut's 'll be update too, but i 'll search to see if there's a way to keep them, but i can't guarantee it to you.

**Comment by kennedyoliveira** [comment]
Hey @jothirams, i updated the workflow to work like you suggested, now the updates and showed in a second line together with the results of a conversion, checkout the new version you can see a example there!

About the problem of losing the shortcuts, its something i can't fix, because its just like alfred works, i searched and didn't found a solution =/

**Comment by jothirams** [comment]
@kennedyoliveira Awesome.. It just works superbly.. Thanks a lot for the quick support.
